### PR TITLE
refactor: Rename consensus tasks and split storage (BFT-476)

### PR DESCRIPTION
**Pull request by aakoshh**
## What ❔
* Renames `FetcherTask` to `ExternalNodeTask`
* Moves `run_main_node` to `mn::run_main_node` to match `en::run_external_node`
* Splits `consensus::storage` into `consensus::storage::connection` and `consensus::storage::store`

## Why ❔

I'm working on https://github.com/matter-labs/zksync-era/pull/2340 where I made these changes either because the naming was confusing or the module was getting very long and I thought it would make it easier to have it in two before adding more trait implementations to it. The PR was getting huge even before I did any actual work, so I decided to make a pure refactoring PR to make the other one easier to review later.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Review by brunoffranca — APPROVED** [review]
Looks good!

**Comment by popzxc** [comment]
image

Is it expected that the contracts submodule was updated?

**Comment by aakoshh** [comment]
@popzxc no, I don't know why it did that. Could it be a side effect of `zk init`? Sorry, I missed that. It would explain why one of the tests [failed](https://github.com/matter-labs/zksync-era/actions/runs/9744720297/job/26904060256) with this:
```
x  Failed to parse config file "/usr/src/zksync/contracts/l1-contracts/script-out/output-deploy-erc20.toml".
|  
!    0: TOML parse error at line 5, column 8
|    |
|  5 | mint = 174085318024506600000000000.0
|    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|  invalid type: floating point `17[408](https://github.com/matter-labs/zksync-era/actions/runs/9744720297/job/26904060256#step:7:409)5318024506600000000000.0`, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 32] bytes
|  
—  Failed to run command
```

**Comment by popzxc** [comment]
@aakoshh I think it happened during the merge, e.g. you updated `main` (which had updated submodule revision) but didn't update it via `git submodule update --recursive`, and then you committed the (old) revision checked out locally.

@brunoffranca please check the PR for suspicious things; if something doesn't seem to belong to the PR, it's generally better to ask about it.

**Pull request merged**
