### PR TITLE
chore(docs): update docs

### PR DESCRIPTION
**Pull request by penghuarong**
# What ❔

- update docs

## Why ❔

- update docs

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Review by popzxc — APPROVED** [review]
Thanks

**Comment by popzxc** [comment]
@penghuarong Looks liks after merging the most recent main, the lints CI job fails. Could you please run `zk fmt`?

**Comment by penghuarong** [comment]
image
How are the numerous errors merged when running the zk lint command?

**Comment by popzxc** [comment]
It's because DAL crate has been changed. Most likely, you need to run `zk init` before `zk fmt` to apply migrations to your local database.

**Comment by penghuarong** [comment]
> image How are the numerous errors merged when running the zk lint command?

@popzxc

**Comment by penghuarong** [comment]
> It's because DAL crate has been changed. Most likely, you need to run `zk init` before `zk fmt` to apply migrations to your local database.

image
What should I do?

**Comment by popzxc** [comment]
Does it happen during `zk init`?

**Comment by penghuarong** [comment]
> Does it happen during `zk init`?

zk lint

**Comment by popzxc** [comment]
As I mentioned above, you need to run `zk init` first, so that new migrations are applied to the database.

**Comment by popzxc** [comment]
Alternatively, you may run `zk fmt prettier` to avoid formatting Rust code. It may work without having to run `zk init`.

**Comment by penghuarong** [comment]
> Alternatively, you may run `zk fmt prettier` to avoid formatting Rust code. It may work without having to run `zk init`.

Awesome, thank you very much

**Review by popzxc — APPROVED** [review]

**Pull request merged**
