### PR TITLE
fix: several typos in the documentation

### PR DESCRIPTION
**Pull request by tudorpintea999**
## What ❔

I fixed some typos in the documentation.

## Why ❔

For a clear and smoother learning experience.

## Checklist

Hope it helps.
Br,
Tudor.

### CODE REVIEW

**Review by perekopskiy — CHANGES_REQUESTED** [review]
Please, format the text using `zk fmt`

**Comment by tudorpintea999** [comment]
hello, tried to configure the project locally but I got the following errors,

Note that I firstly installed all the utils from here https://github.com/matter-labs/zksync-era/blob/main/docs/setup-dev.md

this is my bash_profile content 

export ZKSYNC_HOME=/Userspinteatudor/Documents/GitHub/zksync$
export PATH=$ZKSYNC_HOME/bin:$PATH


`warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.08s.
yarn run v1.22.19
warning package.json: No license field
error Command "zk" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
pinteatudor@192 bin % ./zk init
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/infrastructure/zk/build/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by RomanBrodetski** [comment]
Please try again following https://github.com/matter-labs/zksync-era/blob/main/docs/guides/setup-dev.md - thanks!

**Comment by perekopskiy** [comment]
Closing as stale

**Pull request closed without merging**
