### PR TITLE
docs: convert core and prover docs to mdbook project and add CI

### PR DESCRIPTION
**Pull request by antonbaliasnikov**
## What ❔

* [x] Convert `docs` core project documentation to [mdBook project](https://rust-lang.github.io/mdBook/)
* [x] Convert `prover/docs` prover project documentation to [mdBook project](https://rust-lang.github.io/mdBook/)
* [x] Add CI workflows to build, test, and deploy versioned documentation for these projects using https://github.com/matter-labs/deploy-mdbooks action

## Why ❔

Fixes https://github.com/matter-labs/zksync-era/issues/3185

To improve documentation visibility and usability in ZKsync era repository.

## Tests

Deployed documentation examples are available in the fork:
* For core project: https://antonbaliasnikov.github.io/zksync-era/core/latest/
* For prover project: https://antonbaliasnikov.github.io/zksync-era/prover/latest/

## Design decisions

It was chosen to use two different workflow files for documentation deployments to keep CI reliable and easy to support regardless of a bit of boilerplate code. [Solution with the unified workflow](https://github.com/antonbaliasnikov/zksync-era/blob/main/.github/deploy-docs.yml) for both projects was implemented but rejected as it is overcomplicated and more difficult to support in the long term.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zkstack dev fmt` and `zkstack dev lint`.

### CODE REVIEW

**Review by popzxc — COMMENTED** [review]
Hey! Changes LGTM, but looks like linter is not happy about changes to markdown files. You probably need to run `zkstack dev fmt` / `zkstack dev lint` and/or allow certain warnings if they make no sense.

**Comment by antonbaliasnikov** [comment]
@popzxc , I fixed all issues. Please take another look when possible.

**Comment by popzxc** [comment]
@antonbaliasnikov the CI is green, but the diff is now over 200k lines for some reason 😅

**Comment by antonbaliasnikov** [comment]
New rebased PR is here https://github.com/matter-labs/zksync-era/pull/3275

**Pull request closed without merging**
