### PR TITLE
docs(README): Enhanced README.md with additional details required

### PR DESCRIPTION
**Pull request by mankzan**
Added link for repositories.md for a user to easily navigate to all the repositories, Enhancing the document usability.

### CODE REVIEW

**Comment by Fixue** [comment]
This is airdrop farming, with a high chance of botting/automatisation, that make the work harder for real contributors, repos reviewers and injust to the user.

I would strongly recommand to close that type of PRs for the time being to contain the post-airdrop spam there's going to be due to some Twitter engagement bait post, to avoid proliferation, and doing the changes yourself if needed.

By rejecting those unmeaningful farming PRs, that newly found "github farm" strategy will be considerated ineffective and the spam will soon end, for the benefit of reviewers, devs, users and tech.

If you're doing that with no malicious intent, please consider doing more meaningful contributions.

**Comment by mankzan** [comment]
have you checked the contribution, I have literally added link for repository which would help to get to all the repos for the user who is reading the file. And you created your account just 4 days ago, what are you even doing ser ?

**Comment by Fixue** [comment]
> have you checked the contribution, I have literally added link for repository which would help to get to all the repos for the user who is reading the file. And you created your account just 4 days ago, what are you even doing ser ?

Unmeaningless PR to farm airdrop, nothing else.

What does my account have to do with it, i'm not the one github farming.

**Comment by HoseinNikmaramOfficial** [comment]
thank you :)

**Pull request closed without merging**
