### PR TITLE
refactor: Improve EN Grafana dashboards

### PR DESCRIPTION
**Pull request by brunoffranca**
## What ❔
Adding more information to the EN Grafana dashboards, which barely had any.

## Why ❔
Better observability.

Fixes BFT-507

### CODE REVIEW

**Comment by brunoffranca** [comment]
Checked that it works on my EN. Some documentation fixes are still to be done (on the external node guide).

**Comment by Deniallugo** [comment]
why it's not a part of era observability?

**Comment by brunoffranca** [comment]
It's simpler for the user, there's no need to start a separate service. Besides we already start a Prometheus and Grafana containers together with the EN, it doesn't make sense to start yet another set of containers with era-observability.

**Review by pompon0 — APPROVED** [review]
Approved, but it is not like I manually reviewed the generated json files :P

**Comment by brunoffranca** [comment]
Well, you can always import the dashboard.

**Pull request merged**
