### PR TITLE
chore(docker): use zksync-build-base as a builder image

### PR DESCRIPTION
**Pull request by montekki**
## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.
- [ ] Spellcheck has been run via `zk spellcheck`.
- [ ] Linkcheck has been run via `zk linkcheck`.

### CODE REVIEW

**Comment by popzxc** [comment]
Looks like we're still running [the same apt-get commands and stuff ](https://github.com/matter-labs/zksync-era/actions/runs/7737672602/job/21102633031#step:8:67). Shouldn't it have been solved by the base image or am I missing something here?

**Comment by montekki** [comment]
I am going to merge this and proceed with similar docker files for CUDA and the runner that still runs apt-get and such

**Comment by alkindivv** [comment]
still the same apt-get command?

**Comment by Saurav123461** [comment]
> 🎉 🌮 🎸 🚀

Not often

**Pull request merged**
