### PR TITLE
refactor(dal): strong typing for TEE proof status

### PR DESCRIPTION
**Pull request by pbeza**
## What ❔

Introduce strong typing for the TEE proof generation status in the Rust code only (_not_ in the database). This is a followup for:
- https://github.com/matter-labs/zksync-era/pull/2474#discussion_r1703671929
- https://github.com/matter-labs/zksync-era/pull/2474#discussion_r1706576022

This PR also aligns the status types with those [implemented](https://github.com/matter-labs/zksync-era/blame/7b9e7bf249157272f2c437b86e88d382dd845618/core/lib/dal/src/proof_generation_dal.rs#L22-L23) in `proof_generation_dal.rs` (specifically the `unpicked` status introduced in https://github.com/matter-labs/zksync-era/pull/2258).

## Why ❔

Strong typing makes it easier to reason about the code and helps protect against subtle bugs.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Comment by pbeza** [comment]
I'm not sure why the CI is [erroring out](https://github.com/matter-labs/zksync-era/actions/runs/10559774673/job/29251906455?pr=2733) on code I haven't even touched. 🤷‍♂️

**Comment by popzxc** [comment]
I've shared some thoughts on the subject [elsewhere](https://github.com/matter-labs/zksync-era/pull/2486#issuecomment-2311599788). In short, I would love to see what do we gain from this change (considering cons mentioned there) besides having strong typing as a fact.

**Comment by popzxc** [comment]
@perekopskiy could you PTAL?

**Review by perekopskiy — APPROVED** [review]

**Comment by perekopskiy** [comment]
nit: it's not chore but rather refactor

**Pull request merged**
