### PR TITLE
chore: replace `assert!(matches!(...))` with `assert_matches!(...)`

### PR DESCRIPTION
**Pull request by pbeza**
## What ❔

Replace `assert!(matches!(...))` with `assert_matches!(...)`.

## Why ❔

To make the code more idiomatic.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Comment by pbeza** [comment]
I didn't know we [disallow](https://github.com/matter-labs/zksync-era/actions/runs/10528257525/job/29173375809?pr=2723) unstable features:

```
error: use of an unstable feature
 --> core/lib/types/src/lib.rs:7:12
  |
7 | #![feature(assert_matches)]
  |            ^^^^^^^^^^^^^^
  |
  = note: requested on the command line with `-D unstable-features`
```

so I give up this PR for now. Waiting for it to become a standard Rust feature. It's amazing [how long people can debate](https://github.com/rust-lang/rust/issues/82775) over what seems like trivial features. :P

**Comment by popzxc** [comment]
> I didn't know we [disallow](https://github.com/matter-labs/zksync-era/actions/runs/10528257525/job/29173375809?pr=2723) unstable features

@pbeza We do. We only use nightly because we're forced to (crypto deps), but we want to eventually get back to `stable`. Any nightly feature makes it harder.

However, [we have `assert_matches` in our dependency tree already](https://github.com/matter-labs/zksync-era/blob/0a5ff59de9b3cb8db221017dcfb2e6dcf6e8d6a6/Cargo.toml#L108), so you can simply add it to `dev-dependencies`.

**Comment by pbeza** [comment]
Fixed 🫡 @popzxc, PTAL

**Review by popzxc — DISMISSED** [review]

**Comment by pbeza** [comment]
@popzxc, this PR was removed from the [merge queue](https://github.com/matter-labs/zksync-era/queue/main) due to [failed](https://github.com/matter-labs/zksync-era/actions/runs/10593951177/job/29358454638) status checks:
```
running unit tests with 'cargo nextest run --release '
error: duplicate key `workspace` in table `dev-dependencies`
  --> core/lib/multivm/Cargo.toml:45:1
   |
45 | assert_matches.workspace = true
   | ^
   |
error: failed to load manifest for workspace member `/usr/src/zksync/core/bin/block_reverter`
referenced by workspace at `/usr/src/zksync/Cargo.toml`
```
It doesn't make sense for me – [there is no duplicate there](https://github.com/matter-labs/zksync-era/pull/2723/files#diff-8736210f791af93922cbbb3b912c7abc86dc90479611dc9f97aef4f403a302f1).

**Comment by popzxc** [comment]
@pbeza `assert_matches` was just [added to the multivm deps](https://github.com/matter-labs/zksync-era/blob/main/core/lib/multivm/Cargo.toml#L43) by another PR that got merged before yours.
Merge main, resolve the issue, and push.

**Review by popzxc — APPROVED** [review]

**Pull request merged**
