### PR TITLE
chore: fix docs

### PR DESCRIPTION
**Pull request by MattewGraham**
## What ❔

- Delete unused invalid links
- Fix incorrect line 
- Delete inaccessible links

## Why ❔

I believe having comprehensive documentation is important and will be more developer-friendly.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.
- [x] Spellcheck has been run via `zk spellcheck`.

### CODE REVIEW

**Comment by MattewGraham** [comment]
@dutterbutter  pls review

**Comment by dutterbutter** [comment]
@MattewGraham the removed links are intentional and used internally. Please add them back.

**Comment by MattewGraham** [comment]
> @MattewGraham the removed links are intentional and used internally. Please add them back.

Done

**Comment by dutterbutter** [comment]
@MattewGraham please add back the link from `core/lib/multivm/src/versions/vm_virtual_blocks/README.md` its intentional.

**Comment by MattewGraham** [comment]
> @MattewGraham please add back the link from `core/lib/multivm/src/versions/vm_virtual_blocks/README.md` its intentional.

Sorry; corrected

**Comment by dutterbutter** [comment]
@MattewGraham you removed the link from `docs/guides/advanced/pubdata.md` this is also intentional. Please add it back. The only relevant change here is to the corrected line from `docs/guides/advanced/how_transaction_works.md`

**Comment by MattewGraham** [comment]
> @MattewGraham you removed the link from `docs/guides/advanced/pubdata.md` this is also intentional. Please add it back. The only relevant change here is to the corrected line from `docs/guides/advanced/how_transaction_works.md`

Ok

**Comment by MattewGraham** [comment]
pls merge

**Review by dutterbutter — APPROVED** [review]

**Pull request merged**
