### PR TITLE
refactor(multivm): Remove commented out tests in old vms

### PR DESCRIPTION
**Pull request by popzxc**
## What ❔

Removes commented tests from (very) old VMs.

## Why ❔

- These tests are very dated, and it's highly unlikely that they'll ever be fixed.

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.
- [ ] Spellcheck has been run via `zk spellcheck`.
- [ ] Linkcheck has been run via `zk linkcheck`.

### CODE REVIEW

**Comment by Deniallugo** [comment]
I still want one day to return this tests with backward compatibility of contracts repo ...

**Comment by popzxc** [comment]
When we'll have time for that, ~~a poor soul~~ would be able to use git history to find them. Or will write them from scratch.

I've tried fixing these tests once, it wasn't easy at all, so realistically I doubt anyone would do that in practice.

**Comment by Deniallugo** [comment]
now, it's impossible to fix them we need old bootlader

**Comment by popzxc** [comment]
So, do you mind removing them then? :)

**Review by Deniallugo — APPROVED** [review]

**Pull request merged**
