### PR TITLE
docs: corrected spelling in deeper_overview.md file

### PR DESCRIPTION
**Pull request by bskrksyp9**
Made changes to misspelled words.

## What ❔

Auxiliary is the correct spelling, but `Auxilary` has been used even in the coding part, only comment has been rectified, in this commit. 

## Why ❔
Because spelling was incorrect.

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.
- [ ] Spellcheck has been run via `cargo spellcheck --cfg=./spellcheck/era.cfg --code 1`.

### CODE REVIEW

**Review by RomanBrodetski — APPROVED** [review]

**Comment by RomanBrodetski** [comment]
@bskrksyp9 please check why the CI is failing - thanks

**Comment by bskrksyp9** [comment]
But all i did is just a spell fix and that too from online console, i have no environment setup for this even

**Comment by bskrksyp9** [comment]
> @bskrksyp9 please check why the CI is failing - thanks

I just saw it said `lint` issue with PR title, but I had changed it very next moment when the PR was made, I don't know why it's still showing old issue...

**Comment by Deniallugo** [comment]
Thank you for your contribution. We are working on an automatic spell-checking tool and will not accept PRs with spelling corrections.

**Pull request closed without merging**
