### PR TITLE
test: Fix / log details of flaky integration tests

### PR DESCRIPTION
**Pull request by slowli**
## What ❔

- "Debug sending erc20 token in a block" test may fail because of overly strict matches (traces for a miniblock may contain traces for transactions generated by other tests; some of these transactions may fail).
- Some other integration tests hang up or fail for unclear reasons. This PR adds logging to such tests, so that their failures can be better localized.

## Why ❔

Flaky tests bad.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.
- [x] Spellcheck has been run via `zk spellcheck`.
- [x] Linkcheck has been run via `zk linkcheck`.

### CODE REVIEW

**Comment by slowli** [comment]
Curiously enough, [I've rerun CI](https://github.com/matter-labs/zksync-era/actions/runs/7783159222/job/21227682214) on this PR around 7 times, but haven't been able to catch a single bug that this PR aims to localize 🙃 I've observed them on my other PRs, so IMO this PR still makes sense.

**Review by popzxc — APPROVED** [review]

**Comment by popzxc** [comment]
Sike!

**Comment by slowli** [comment]
@popzxc Well, [one of the failed CI jobs](https://github.com/matter-labs/zksync-era/actions/runs/7796205183/job/21260461237) was useful at least; it did fail on the logged tests, so we now have some more info to investigate.

**Comment by popzxc** [comment]
Yeah, my comment was only about the fact that our CI works in mysterious ways.

**Pull request merged**
