### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by MoneyBund**
## What ❔

fix typo

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.
- [x] Spellcheck has been run via `cargo spellcheck --cfg=./spellcheck/era.cfg --code 1`.

### CODE REVIEW

**Comment by MoneyBund** [comment]
> Hi @MoneyBund, thanks for contribution! Please do not re-open PR or commit to this branch if you want it merged :) . We currently have some issues with merging external PRs so it can take some time.

What's the problem?

**Comment by perekopskiy** [comment]
> What's the problem?

We run CI for external contributions differently and it's flaky, we're working on improving this

**Comment by MoneyBund** [comment]
> > What's the problem?
> 
> We run CI for external contributions differently and it's flaky, we're working on improving this


Is it ok?

**Comment by MoneyBund** [comment]
@perekopskiy

**Pull request closed without merging**
