### PR TITLE
chore: Some typo and grammar fix.

### PR DESCRIPTION
**Pull request by FarukhS52**
# What ❔

typo and grammar fixes in various files

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [ x] Documentation comments have been added / updated.
- [ x] Code has been formatted via `zk fmt` and `zk lint`.

### CODE REVIEW

**Comment by FarukhS52** [comment]
@RomanBrodetski can it be merged?

**Comment by popzxc** [comment]
@FarukhS52 looks like CI lints job fails. Could you please run `zk fmt`?

**Comment by FarukhS52** [comment]
@popzxc , actually i am new to github and i don't know about how to work with these commands

**Comment by FarukhS52** [comment]
Can you tell me where should i run that command

**Comment by popzxc** [comment]
There are instructions on how to set up the repository: [setup_dev.md](https://github.com/matter-labs/zksync-era/blob/main/docs/setup-dev.md) and [development.md](https://github.com/matter-labs/zksync-era/blob/main/docs/development.md).
When you'll be able to run `zk` tool, you can use `zk fmt` to fix the formatting.

**Pull request closed without merging**
