### PR TITLE
feat: Start using a new test harness interface without generics

### PR DESCRIPTION
**Pull request by mm-zk**
## What ❔

* Start using the new version of the 1.4.2 test harness, that doesn't export generics

## Why ❔

* This should improve the compilation speed.

### CODE REVIEW

**Review by popzxc — DISMISSED** [review]
Trusting you on the fact that changes in `Cargo.lock` are checked and valid 😅

**Review by RomanBrodetski — DISMISSED** [review]
Oh this is good

**Comment by RomanBrodetski** [comment]
@mm-zk I'd say this is not a `chore` but a `feat`. Would want to see this in changelog

**Review by popzxc — APPROVED** [review]

**Comment by mm-zk** [comment]
@RomanBrodetski - done, PTAL

**Review by popzxc — APPROVED** [review]

**Pull request merged**
