### PR TITLE
feat(zk_toolbox): Add setup keys step to prover init

### PR DESCRIPTION
**Pull request by matias-gonz**
## What ❔
Add setup keys step to prover init

### CODE REVIEW

**Review by Deniallugo — APPROVED** [review]
LGTM, but i'm waiting for @EmilLuta or @Artemka374

**Comment by Artemka374** [comment]
I don't think that generating/downloading setup keys by default is a good idea. It can take a lot of time(generating ~40minutes/downloading depends on your internet connection, but it is 26GB anyway), and it is needed only for FRI provers. Instead, I'd add an option to choose whether you want to download setup keys right now or not. The same also refers to initializing bellman-cuda - for that I need drivers/CUDA and other things, but it is used only in compressor. I don't need it e.g. [here](https://github.com/matter-labs/zksync-era/pull/2800), where bellman cuda is baked into compressor's image. Same way it can be changed for downloading compressor setup key, but it is small, so it definitely wouldn't hurt to have it by default

**Comment by matias-gonz** [comment]
Hello @Artemka374 right now it is optional to download/generate setup keys and the [default is false](https://github.com/matter-labs/zksync-era/pull/2811/files#diff-18bdfce168eddebd57cf0d13a909d5e2209ff2bb7be93c8d348be5c1a0dd0b12R375-R379)

I will make downloading the compressor key and setting up bellman-cuda default false too.

**Comment by Artemka374** [comment]
@matias-gonz I'd suggest not to make compressor key dowloading optional because we don't have alternative command to do that later... So it's either leave it as is, or add separate command for this

**Comment by matias-gonz** [comment]
@Artemka374 compressor key downloading was already optional. I will add a separate command

**Review by Artemka374 — APPROVED** [review]
LGTM!

**Review by Deniallugo — APPROVED** [review]

**Pull request merged**
